# Written by Checkmk store

agent_signature_keys.update({1: {'alias': 'cmk',
     'certificate': '-----BEGIN CERTIFICATE-----\n'
                    'MIIC1DCCAbwCAQEwDQYJKoZIhvcNAQEFBQAwLzEaMBgGA1UECgwRQ2hlY2tfTUsg\n'
                    'U2l0ZSBnaXQxETAPBgNVBAMMCGNta2FkbWluMCAXDTIzMDQwNTE5MTkxN1oYDzIw\n'
                    'NTMwMzI4MTkxOTE3WjAvMRowGAYDVQQKDBFDaGVja19NSyBTaXRlIGdpdDERMA8G\n'
                    'A1UEAwwIY21rYWRtaW4wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDe\n'
                    'mZz/g7oiDvW/p9pwi6ECYb9tXt8ZoktOSR5EN5ICRNz+61eykapVGR1NeK3z+ddn\n'
                    'rmGnDp4xqRfJWyXyanTzUP4SWkPzehsd9RFnzM7Zs1QF01NbbwgqW1jyel5J56kC\n'
                    'nYh8DdYdlcJRX561PnkOtceJLLp8Ix0MXji7pEzn4UbVBYxJVnSPM2ZcPKq6sf4w\n'
                    'G08NnyAxcIwADZ4ZyvTtH0fF+f/gt+bmJPbBqnSbXlTRnW7lrmyUlR0E4pIeabJi\n'
                    'OmlpjDGEEUGeY6Ap3R9FpkfxmT4yO9P3DEsHViuSkYSvut82l+k5e4gcm94HDOSh\n'
                    'LXYLm3LGbRetT63d/2jHAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAE7k5d7mASWJ\n'
                    'PATeOAoMJIZIPUzh8lETCpwFEGOdeJbc8YPawZyDgkx6kMCcoENqGHwkKGASikWG\n'
                    'OKA+L2SDV1/AnlovQtIeqSnyQ6kiOphWnvXYpqegOSecgDlO+EBXFfmN8i/sjHYM\n'
                    'Y+p1V9YCOJedXw5Z7cR5oSdZRaClzmyJJ7DfqZWt5obxmmR2VFoCSPgnLRSTugIK\n'
                    'Gdmvevp01D5HuzVFPhaYAKc2LDAFEJ1odHDXhIDOOBfhNUFljQoF3Gi68cOHq4eq\n'
                    'a2B/uRTYss6J0iIbq7/T8Y43hQiB4ZOILchBoWk0Er7GrlzdDjrnzrpgy3AFKqRc\n'
                    'mWdvZAj19lc=\n'
                    '-----END CERTIFICATE-----\n',
     'date': 1680722357.7591667,
     'owner': 'cmkadmin',
     'private_key': '-----BEGIN ENCRYPTED PRIVATE KEY-----\n'
                    'MIIFLTBXBgkqhkiG9w0BBQ0wSjApBgkqhkiG9w0BBQwwHAQIBITBldnEZqwCAggA\n'
                    'MAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBB0GxoHXhy33Th1EtmeGGDGBIIE\n'
                    '0L+IPIs9h1QVICr/nt8iZlpwvNsT97qVA012McRM17/A+T6xUen/dBQGDlC/q/ez\n'
                    '0RPe4olzeuMLQyxB/lPDUpPTEyLC5Nz8jKfov/RJfsOqnueckoNFxpYhQqQ/BQy7\n'
                    'BZXQFXzbtGOuI5dtjZzMTDMiLy6arl88+Vx/WvvDqltXvmuTMDP9Nhzre0SDRHHu\n'
                    'YaU9zcRdSpGnynkl7ZiMlzggSzU9LsTgo3HTCF92K1hFUvugS7KlHl3Tm0m/gKe+\n'
                    'P4SpobP1xHZpd4bkrFy2yzeNuKYNg8N6hYalbDvR+M+nnKtT5xgz/A0sL5ixAhMX\n'
                    'Q+rzjwdSCUWaB8J+SkbA51qCYy5IpJXU7SoxRPmS46/NSJN+6eCTr4OTh6MP//3s\n'
                    '3iHxF9o84RpbTAi1OU+X2digV6h4uBn2BsApkc3W9iCv9fGB80EJaKUQiv0pR1Jg\n'
                    'wvXFrevceYvT/X6BAh4ZRXO6xF2HijoRcvXv/wHa5QcmA6T0YEItEmtluJBepCyV\n'
                    '2kKubl8uFXQZppengxl50LfrOzhrstUxTlJummBNgunCK/zkcjUJ1bLFAOFVTdCh\n'
                    'BKqxUDIxaRzUFcFD5MjAkkkPKK+WoYHE3OgiYbQ0FQpfIYxqgJxawuTDUE+0Yy39\n'
                    'UK9p5Uvir3VWVkHu/nsIDmXEs1rvdj8fdF+HO78oM2uK27Rzvig2gI9S4EsiohYH\n'
                    'd6Pn2kdv2r5bXwBynOOgtqMB326q1o7AMMbaGfUnaLj9ANsF8wExh73b9TFQLsAX\n'
                    '+1Q2gKB8XzKn8ElIfyBm+77kFIPy3Sc6Mh9EFFUNg1ew4QKZ05+Ah/GQj9PmJna/\n'
                    'KOVIN7tPBATflE3wiUpTi4gZoSPo+qUj9H6hB/1fUw4OspZDZjWUi5+FZGggL3Aq\n'
                    'DNb/4SL7Si+9PRg31dMkhpCjCcku2UoHHIbIBfkhZ2ZS8t2CNMZTBRKZAMML5mkr\n'
                    '9qo2xArBHj4cRY26D2SX4FxuvAYtJLh/Z5YZrIxbs381UP15f1gfecoy3YG0EYcJ\n'
                    'r2wQ52ToGKR35HfMdY+4wz/OYa8/3x9bvaWItGV4cK3JWIj9FjBRfDhM56HN1I9Q\n'
                    'll7RbzL4/xHuED2vbfRV3kgQOOosCvJhGv8dQ3urg1+Snxx2qPT3YdFgY7Wh5nr+\n'
                    'nZPetPQ+3/xI0XOv01hAoOnHIJ/TpkNpNUCl7BWMJ5Jc8uN9xHyNByNGPDY/R62W\n'
                    'SKeFXr2A0sujvyxADEI+DpAWWsZbvyNhsLutp2RHxhpWFoLJEcI/SkxOBbh+okYv\n'
                    'xFRded/vZv+XVsmUZCPNe4kZ3o/Qk1vrDhfkynz9Ng3eMNulxuMW6pMuIbmoXZuI\n'
                    'LJQ+pwPao7sFCEn7+Eao1kGRY5HTbUd7o4G3T6K+y8J59lX0mT0khdFWTmxoXWd8\n'
                    'SbCWWKMRnzeSGCebJlRFSAwb8+poLQGbqnxIxgNJC7Yt9w60S97dsVVU1tEJH50p\n'
                    'wJXLlYPrC8qGzXpkQjowomwi6GHTlEFvuNLV4lvDnwHJfgO8UM6qK+5H66zdOKYG\n'
                    'vS1CIoKbLvz/PO6wWT34rH5jct8tUw0iU3Vf5MMEIfmEvfG2UBGYmrimDhzgauwa\n'
                    'wCmzJjFzioG/y/OrSOBc9TIK5w2pWXvRH5ZWVlgj4VHJ\n'
                    '-----END ENCRYPTED PRIVATE KEY-----\n'}})
