# Created by WATO

trusted_certificate_authorities = {'trusted_cas': ['-----BEGIN CERTIFICATE-----\n'
                 'MIIDEzCCAfugAwIBAgIUBTY9+8llNhEe2bTU19irNz8ExVQwDQYJKoZIhvcNAQEL\n'
                 'BQAwHzEdMBsGA1UEAwwUU2l0ZSAnZ2l0MicgbG9jYWwgQ0EwIBcNMjMwNDA3MjE1\n'
                 'MTAzWhgPMzAyMTA4MDgyMTUxMDNaMB8xHTAbBgNVBAMMFFNpdGUgJ2dpdDInIGxv\n'
                 'Y2FsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuLh55rJkN89Q\n'
                 'nXxfOAfCjn77R1lyot1ccaaOPhLmt3VKWb/fdkp2evfCfJxsTgbv+AzUkIUti3z9\n'
                 'rLJaTkd5mIJp6PbD+a/+ez4BUigY63SdPRuBteSg3SWobCU26+xGFkq4jhMq1XO6\n'
                 '2kvjm5l7emoZgKM5LzlTagLL8w1TYJX4N5EXSg0KwUJjj0wi4pc1jzfKLllJ4Cou\n'
                 'A3USOH5qhGT4DBWfm3RHKP+n/Qzi3zdb6qUehcGL3eebWnzIHNFCTZyjpWmfzfCI\n'
                 'XDvbsDtX5DTOg5BxrU6PnO011tDovkbyBhaIpfmxwzdJbcbC+0+EGeDMVMg1lTFh\n'
                 'MilDxIGYwwIDAQABo0UwQzAdBgNVHQ4EFgQUN/vS8W+P/F/3GqVdwTog2j/tw/Ew\n'
                 'EgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQEL\n'
                 'BQADggEBAGmf6itJLy0HmDL2XSv77Hy4B6MXDaZp2+CAml+lUtZ6nSK0KmHb1Iez\n'
                 'w+IYqCzzH6/KewUaROd9ckB/SxRUljvKCEfudcX5W3pDur3k7XSIoDUC2HoPZ4fu\n'
                 'xDUcB6niNa6musOIwDRU29zwCrOCfDFlJsZdXg9ZupCZKERvch+QE7gfO0/VLx4s\n'
                 'tE6T4qCSKmmRV9I523SBL3lDk5TMRLQoUuIiIEYEyYKCCB/0CkjUoOm8VytyfonS\n'
                 'sGVGqq+AlCwImjXCKg7hyRLgCVAEDzeV6oSx+Gm1WkiAXb172vSodQeHjS79CoyF\n'
                 'ZrTMhT6J/pV1dZzGIqA2hhFIucfKlR0=\n'
                 '-----END CERTIFICATE-----\n',
                 '-----BEGIN CERTIFICATE-----\n'
                 'MIIDEzCCAfugAwIBAgIUAfIBdGAgTMTZFhp9cU5m4HINVEQwDQYJKoZIhvcNAQEL\n'
                 'BQAwHzEdMBsGA1UEAwwUU2l0ZSAnZ2l0MycgbG9jYWwgQ0EwIBcNMjMwNDExMjIz\n'
                 'MjU1WhgPMzAyMTA4MTIyMjMyNTVaMB8xHTAbBgNVBAMMFFNpdGUgJ2dpdDMnIGxv\n'
                 'Y2FsIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAut/I5dzcqAp+\n'
                 'Yevs6DXLjCksQk2WmTmFM4mk5SY0OYnt6w0ByABblQEa7ajMhIrR9xKeWxf7pOEp\n'
                 'txUvqaxS2h4fIb7hO7tzUosvcSIPOw2okjj0Y5zjRe0RciAHz5Lf40W8zmz0r8ew\n'
                 'ItQijhqVpFlTWXtkGAJCLrwHY3Ig7omMdf72A8ef6/zR+Xm2s1Z3dHUiACml6dtd\n'
                 'Z1YDli6Zva4SIvCY8GMY7OA8V9R3c11Ry74NCwzN0bAJL+BpUh/QwF+aZ+8BLoWV\n'
                 'o9V5Pv8FbW1o1+kPDCTAO1CW+JmcTPjIMM2WW6CyrHcjSzWcxeT/gHjV9OobOyJV\n'
                 'GrmehL4rLQIDAQABo0UwQzAdBgNVHQ4EFgQUZW2fDbciHl8dmNd0onsHO4ieNUww\n'
                 'EgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQEL\n'
                 'BQADggEBAHLSxbGgkRV+TZwBwZwJcfZw1+UC2WPH7B8XP16nOpv+ADqIBwMmz+2+\n'
                 'OyHWOQ73y94roX81z2WTitaetIoqEfXtyWNvDC3yy9yVs6+Giy2i34SOh4Lxc0Hq\n'
                 'RWzfyPUr11uT9YsujhqHFDO15pwUlbj32BbIeZiPFiETkbQEXn/VJQAoohLkUIHh\n'
                 'yEokvdCLgF7/yQ7va5Jz2DQyCB6PAoUgIWqOrZm2Wm3rqiADw4bddk3Z9Eal4dqM\n'
                 '2XpxBXHI/uVenXyU3MGUdb2pvdnia1EnDcNI1yipdiGt5/XP4g0tIqYaXR6se+iB\n'
                 'LAUM3LK/ouh1BnFlIvyU4OkseGdngSA=\n'
                 '-----END CERTIFICATE-----\n',
                 '-----BEGIN CERTIFICATE-----\n'
                 'MIIBdjCCARygAwIBAgIRANm537JEWN56eliuRj7C2EAwCgYIKoZIzj0EAwIwGTEX\n'
                 'MBUGA1UEAxMOVEhBTk9TIFJvb3QgQ0EwHhcNMjMwNTAzMjEwOTAyWhcNMzMwNDMw\n'
                 'MjEwOTAyWjAZMRcwFQYDVQQDEw5USEFOT1MgUm9vdCBDQTBZMBMGByqGSM49AgEG\n'
                 'CCqGSM49AwEHA0IABC7V7ibcNfyghtwSV6Ii/JzF34NXmF7Sl4hHs/yb2ogbRS0b\n'
                 'j9WG8O2fuLBix+iCXo1jcvaQunCDZ/PGNhdq6LSjRTBDMA4GA1UdDwEB/wQEAwIB\n'
                 'BjASBgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBQ6l4gYg43Mi8MYy9uwobu9\n'
                 'GJB01TAKBggqhkjOPQQDAgNIADBFAiAod/f1ZYcG305AdZ8VGccWM4QvKteiM7Gq\n'
                 'Jq0J1A9gygIhAPIH/V5P8FO9ud2l1ZM+wjDD/UrUZ74f9dT+JK/ALptc\n'
                 '-----END CERTIFICATE-----\n',
                 '-----BEGIN CERTIFICATE-----\n'
                 'MIIDDzCCAfegAwIBAgIUZY3mWpIpd5nycjS94vRIjuETG0IwDQYJKoZIhvcNAQEL\n'
                 'BQAwHTEbMBkGA1UEAwwSU2l0ZSAnYTEnIGxvY2FsIENBMCAXDTIzMDgzMDE5Mjcz\n'
                 'NloYDzMwMjExMjMxMTkyNzM2WjAdMRswGQYDVQQDDBJTaXRlICdhMScgbG9jYWwg\n'
                 'Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCWx/on1rxoJOzAki61\n'
                 '3aanvOeIg/r0RoIuMsevhbTfRbL72VDKL0VgtvmnEuu0ZmWc1TtEIvG1DVJLHTT5\n'
                 '59Nueco32o7av0teCesmLrkyBq5GxIuk9djTypRtOgwmpS4J20eLm9AfU36NM9W1\n'
                 'Iuox2Zlv2gecxBtkuG5IXL6wgxqHZ7hIDgdVLm6c7VQ4p5ztFYxjo3GDeDVDig8w\n'
                 '9PSoic0F9PQxZC0WulVm+xfpgas3l0ztN9wYOVM+AkqFlsZxDaeyr1WCQPJntFMk\n'
                 'SLrmx5I7np2w8/pcgdgDc9B4fhBZWx0WhV9pja0yQRK4Ki9Seyh/iFYefjWRaxIr\n'
                 'o0iRAgMBAAGjRTBDMB0GA1UdDgQWBBQTynXdLBNeWOnxKn1zFLMeTSu2KjASBgNV\n'
                 'HRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOC\n'
                 'AQEAiE0gacCaSa/koHKvi0Xile359OF01ZuTNfOYbEhE1B63Y46ERQx79awdIF1r\n'
                 'XDLGUQm8nFaDoBJfkpjsbiP3ButDiOmPMBfmiaUVVfeIErL/apl5m4Swl+hzNVt+\n'
                 'GPBD8JRaU96re8zKjfKl6YZLqtINfYoL7e+xPdrOMUdy+ziT2ZGgFihdnRB5dCBv\n'
                 'bfyOeQ/rm6/YGzp+QV3hiPPHLw1hmS2Sefub3xstTS1PUkdN3BTPZBByfiAoA8YF\n'
                 'muqfkzDS4ObkuFNm5gQdwNpEvo73mfMh6+ls54+XsTxdVqjDpwhZo+Dbvz/QydIt\n'
                 'L8IzzxwHjRowdNaAB5Za1oFv6Q==\n'
                 '-----END CERTIFICATE-----\n',
                 '-----BEGIN CERTIFICATE-----\n'
                 'MIIDFTCCAf2gAwIBAgIUEui7SoKk50945lY52szGA5m+jDYwDQYJKoZIhvcNAQEL\n'
                 'BQAwIDEeMBwGA1UEAwwVU2l0ZSAnbGRhcDEnIGxvY2FsIENBMCAXDTIzMDkyOTE0\n'
                 'MDIzNloYDzMwMjIwMTMwMTQwMjM2WjAgMR4wHAYDVQQDDBVTaXRlICdsZGFwMScg\n'
                 'bG9jYWwgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC7zwbmvOIz\n'
                 'nUQdARsxSfkHaimVu6yGbC+SiTUiLVaDVy81OxuDe34L6Z0t/nAoQp9x9QEefWm6\n'
                 'yUvxdRtYfV0Ix17O7fvhdl4XYeYIkr8n8st2ATtr78bJzxBFpDmNuvXNZvDFN/Ts\n'
                 'RqdE5kuRza0ap+96V9VmaoKPh/d3LC4iaBqmGxjHZSlKIVr0IlQIjIppUhgGrUyB\n'
                 'bixDN4B/JDHZbW3Os3YJS09Vz+4H3Dj4kM0JbrAorinHg2qgA48RscFu+Y1v2vWK\n'
                 'Exd4p6KxdbJdDFDPwcUngilOtAiN4euxeubKmchxi309LbE+BS1gmIUSAUZLRiEX\n'
                 'GQtY7nlLAGcbAgMBAAGjRTBDMB0GA1UdDgQWBBSSyr9CNg0D+ItoNB+Cy5QzJuY1\n'
                 'TTASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0B\n'
                 'AQsFAAOCAQEAAvHv/0itCKtxtnECs68f9jjqU0CJUVgijnPI8h7Tk9OuqJ3MsJD+\n'
                 '2swbm4bpnbuIArLXX7H23U3DNtuI2ighFavOzt6lEUATYWrnd6QXAFR2a3FLGptc\n'
                 'Evac4kyWLy1zDMjq28asgJOYWdrGXsWDjTrwmX148FzT5BrtFfK38uhPHHWpKpC7\n'
                 'l/3k+auZHSjKvAG121bidHmoNFMog+yGR7tkUr7gHVLJw4flOrr+UwvBD/A4cRUc\n'
                 'I6Ge1suolRc+avnd2EoWsq6yGvbgHXQhBuLAI94HOD/bR0XmMLafyX24gGf4KEcd\n'
                 'VisXpebF9fG4P7BP/2VIZwGBfxrmqqDmvA==\n'
                 '-----END CERTIFICATE-----\n',
                 '-----BEGIN CERTIFICATE-----\n'
                 'MIIDDzCCAfegAwIBAgIUNyrQOHxfSsm2wNx7iY7py01IgOMwDQYJKoZIhvcNAQEL\n'
                 'BQAwHTEbMBkGA1UEAwwSU2l0ZSAnYTEnIGxvY2FsIENBMCAXDTIzMTAxMTEyNTkw\n'
                 'NVoYDzMwMjIwMjExMTI1OTA1WjAdMRswGQYDVQQDDBJTaXRlICdhMScgbG9jYWwg\n'
                 'Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDgffIuFL+b4M+oPjad\n'
                 'xMermQNOzCg4GjUCPcwV/dNGRLPeMj8tnkwIvGigHoUvLgeXBxbvNJLY9sv3FtXj\n'
                 'AkA+3uZzWFOxCjsoP8RerbPEMG4S0RKfufvddO+UvQ3izPR4Dn7oYJ5KE9Dy7iSD\n'
                 'hbWceHAgTXk9oFL7u05cqresykna7FvAXqI95n9BL0Keb7/KK26eCmg0rnLBA+yd\n'
                 'C88D8OO5qUvvHqvlougdaXrl49Qm79EHkktCAfGD9mV8oi1Bj1E0M0vSdt3jwCDE\n'
                 '/GEKZhysdcINcdyQ1vAPjVBnmBU08rk4BFE6hnPO9oOsSFflzzePLFJnkAnZW8bV\n'
                 'aAFBAgMBAAGjRTBDMB0GA1UdDgQWBBRDUuNZVXVDHfeXCabj2CCnjAul6jASBgNV\n'
                 'HRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOC\n'
                 'AQEAL4LaUGL0KCCD4lpa+BYF/o1NKRUi7vHZTzdHcyuEcB6IcJTRQ4SkcSx9ofUI\n'
                 'X/KRJ2baHVlk3aERGRBABrxKk/ajnGh2pAm6yi0z67bj3lFdMBcT9rfzCBTu9nMz\n'
                 'Yshvi6t5VzF90anAFrKNmfs46P754O+cvfKCvmrXceW1D/Y/gGdlT1LObyeXNqN1\n'
                 'yThimKPsGvX4nv2IP4K8PS/JumNYy6eL0jLMCNTeVMTJLkewWdI4ritX6UGRnBru\n'
                 'beAHUQTyQDfNShtLh6GnL7/pSPKZQTO+DNi/NtrwKpAQuGV/lOLZy+Xos2MnlsQk\n'
                 '1fMni+byOi1G7UQktWN3V6H+TA==\n'
                 '-----END CERTIFICATE-----\n'],
 'use_system_wide_cas': True}
