# Created by HostStorage

all_hosts += ['DUMMY', 'localhost2', 'localhost3', 't']

clusters.update({'cluster': ['20230707-GSIAD3DWH01V.txt', '20230707-GSIAD3DWH02V.txt']})

host_tags.update({'DUMMY': {'address_family': 'no-ip',
           'agent': 'no-agent',
           'criticality': 'prod',
           'networking': 'lan',
           'piggyback': 'auto-piggyback',
           'site': 'scooter',
           'snmp_ds': 'no-snmp',
           'test': 'thanos',
           'usa': 'thanos'},
 'cluster': {'address_family': 'ip-v4-only',
             'agent': 'cmk-agent',
             'checkmk-agent': 'checkmk-agent',
             'criticality': 'prod',
             'ip-v4': 'ip-v4',
             'networking': 'lan',
             'piggyback': 'auto-piggyback',
             'site': 'scooter',
             'snmp_ds': 'no-snmp',
             'tcp': 'tcp',
             'test': 'thanos',
             'usa': 'thanos'},
 'localhost2': {'address_family': 'ip-v4-only',
                'agent': 'cmk-agent',
                'checkmk-agent': 'checkmk-agent',
                'criticality': 'prod',
                'ip-v4': 'ip-v4',
                'networking': 'lan',
                'piggyback': 'auto-piggyback',
                'site': 'a1',
                'snmp_ds': 'no-snmp',
                'tcp': 'tcp',
                'test': 'thanos',
                'usa': 'thanos'},
 'localhost3': {'address_family': 'ip-v4-only',
                'agent': 'cmk-agent',
                'checkmk-agent': 'checkmk-agent',
                'criticality': 'prod',
                'ip-v4': 'ip-v4',
                'networking': 'lan',
                'piggyback': 'auto-piggyback',
                'site': 'scooter',
                'snmp_ds': 'no-snmp',
                'tcp': 'tcp',
                'test': 'thanos',
                'usa': 'thanos'},
 't': {'address_family': 'ip-v4-only',
       'agent': 'cmk-agent',
       'checkmk-agent': 'checkmk-agent',
       'criticality': 'prod',
       'ip-v4': 'ip-v4',
       'networking': 'lan',
       'piggyback': 'auto-piggyback',
       'site': 'scooter',
       'snmp_ds': 'no-snmp',
       'tcp': 'tcp',
       'test': 'thanos',
       'usa': 'thanos'}})

host_labels.update({'localhost2': {'ssh': 'yes'}})

# ipaddresses
ipaddresses.update({'localhost2': '127.0.0.1', 'localhost3': '127.0.0.1'})

# Host attributes (needed for WATO)
host_attributes.update({'DUMMY': {'meta_data': {'created_at': 1691171576.0,
                         'created_by': 'cmkadmin',
                         'updated_at': 1697737946.8270566},
           'site': 'scooter',
           'tag_address_family': 'no-ip',
           'tag_agent': 'no-agent'},
 'cluster': {'meta_data': {'created_at': 1688755279.0,
                           'created_by': 'cmkadmin',
                           'updated_at': 1697737946.8273518}},
 'localhost2': {'ipaddress': '127.0.0.1',
                'labels': {'ssh': 'yes'},
                'meta_data': {'created_at': 1683216088.0,
                              'created_by': 'cmkadmin',
                              'updated_at': 1697737946.8275673},
                'site': 'a1',
                'tag_agent': 'cmk-agent'},
 'localhost3': {'ipaddress': '127.0.0.1',
                'meta_data': {'created_at': 1688755178.0,
                              'created_by': 'cmkadmin',
                              'updated_at': 1697737946.8277714},
                'site': 'scooter'},
 't': {'meta_data': {'created_at': 1697044122.0,
                     'created_by': 'cmkadmin',
                     'updated_at': 1697737946.8279696}}})

folder_attributes.update({'/wato/': {'bake_agent_package': True}})
