# Created by HostStorage

all_hosts += ['WWIPU01-pasl2005.ww-intern.de-walk.txt',
 'aha',
 'astiomon-u90c04p01esx03-cimc.cisco.com-walk.txt',
 'astiomon-u90c04p02esx04-cimc.cisco.com-walk.txt',
 'bgl2iomon-u36c01p08esx05-cimc.cisco.com-walk.txt',
 'cs-sec-gw.ad.ed-gruppe.de-walk.txt',
 'intergen-CHCINTERGFW1-walk.txt',
 'lyo-rtr-4th01',
 'twenty-es01.adc.thegrid-walk.txt']

host_tags.update({'WWIPU01-pasl2005.ww-intern.de-walk.txt': {'address_family': 'no-ip',
                                            'agent': 'no-agent',
                                            'criticality': 'offline',
                                            'networking': 'lan',
                                            'piggyback': 'auto-piggyback',
                                            'site': 'scooter',
                                            'snmp': 'snmp',
                                            'snmp_ds': 'snmp-v1',
                                            'test': 'thanos',
                                            'usa': 'thanos'},
 'aha': {'address_family': 'no-ip',
         'agent': 'no-agent',
         'criticality': 'offline',
         'networking': 'lan',
         'piggyback': 'auto-piggyback',
         'site': 'scooter',
         'snmp': 'snmp',
         'snmp_ds': 'snmp-v1',
         'test': 'thanos',
         'usa': 'thanos'},
 'astiomon-u90c04p01esx03-cimc.cisco.com-walk.txt': {'address_family': 'no-ip',
                                                     'agent': 'no-agent',
                                                     'criticality': 'offline',
                                                     'networking': 'lan',
                                                     'piggyback': 'auto-piggyback',
                                                     'site': 'scooter',
                                                     'snmp': 'snmp',
                                                     'snmp_ds': 'snmp-v1',
                                                     'test': 'thanos',
                                                     'usa': 'thanos'},
 'astiomon-u90c04p02esx04-cimc.cisco.com-walk.txt': {'address_family': 'no-ip',
                                                     'agent': 'no-agent',
                                                     'criticality': 'offline',
                                                     'networking': 'lan',
                                                     'piggyback': 'auto-piggyback',
                                                     'site': 'scooter',
                                                     'snmp': 'snmp',
                                                     'snmp_ds': 'snmp-v1',
                                                     'test': 'thanos',
                                                     'usa': 'thanos'},
 'bgl2iomon-u36c01p08esx05-cimc.cisco.com-walk.txt': {'address_family': 'no-ip',
                                                      'agent': 'no-agent',
                                                      'criticality': 'offline',
                                                      'networking': 'lan',
                                                      'piggyback': 'auto-piggyback',
                                                      'site': 'scooter',
                                                      'snmp': 'snmp',
                                                      'snmp_ds': 'snmp-v1',
                                                      'test': 'thanos',
                                                      'usa': 'thanos'},
 'cs-sec-gw.ad.ed-gruppe.de-walk.txt': {'address_family': 'no-ip',
                                        'agent': 'no-agent',
                                        'criticality': 'offline',
                                        'networking': 'lan',
                                        'piggyback': 'auto-piggyback',
                                        'site': 'scooter',
                                        'snmp': 'snmp',
                                        'snmp_ds': 'snmp-v1',
                                        'test': 'thanos',
                                        'usa': 'thanos'},
 'intergen-CHCINTERGFW1-walk.txt': {'address_family': 'no-ip',
                                    'agent': 'no-agent',
                                    'criticality': 'prod',
                                    'networking': 'lan',
                                    'piggyback': 'auto-piggyback',
                                    'site': 'scooter',
                                    'snmp': 'snmp',
                                    'snmp_ds': 'snmp-v1',
                                    'test': 'thanos',
                                    'usa': 'thanos'},
 'lyo-rtr-4th01': {'address_family': 'no-ip',
                   'agent': 'no-agent',
                   'criticality': 'offline',
                   'networking': 'lan',
                   'piggyback': 'auto-piggyback',
                   'site': 'scooter',
                   'snmp': 'snmp',
                   'snmp_ds': 'snmp-v1',
                   'test': 'thanos',
                   'usa': 'thanos'},
 'twenty-es01.adc.thegrid-walk.txt': {'address_family': 'no-ip',
                                      'agent': 'no-agent',
                                      'criticality': 'offline',
                                      'networking': 'lan',
                                      'piggyback': 'auto-piggyback',
                                      'site': 'scooter',
                                      'snmp': 'snmp',
                                      'snmp_ds': 'snmp-v1',
                                      'test': 'thanos',
                                      'usa': 'thanos'}})

# Host attributes (needed for WATO)
host_attributes.update({'WWIPU01-pasl2005.ww-intern.de-walk.txt': {'meta_data': {'created_at': 1682080231.206638,
                                                          'created_by': 'cmkadmin',
                                                          'updated_at': 1697737946.8559551}},
 'aha': {'meta_data': {'created_at': 1683065489.508209,
                       'created_by': 'cmkadmin',
                       'updated_at': 1697737946.8562043}},
 'astiomon-u90c04p01esx03-cimc.cisco.com-walk.txt': {'meta_data': {'created_at': 1689278504.0,
                                                                   'created_by': 'cmkadmin',
                                                                   'updated_at': 1697737946.8564157}},
 'astiomon-u90c04p02esx04-cimc.cisco.com-walk.txt': {'meta_data': {'created_at': 1689631782.225835,
                                                                   'created_by': 'cmkadmin',
                                                                   'updated_at': 1697737946.856616}},
 'bgl2iomon-u36c01p08esx05-cimc.cisco.com-walk.txt': {'meta_data': {'created_at': 1689278428.1711438,
                                                                    'created_by': 'cmkadmin',
                                                                    'updated_at': 1697737946.8568118}},
 'cs-sec-gw.ad.ed-gruppe.de-walk.txt': {'meta_data': {'created_at': 1683061495.0,
                                                      'created_by': 'cmkadmin',
                                                      'updated_at': 1697737946.8570125}},
 'intergen-CHCINTERGFW1-walk.txt': {'meta_data': {'created_at': 1695875577.0,
                                                  'created_by': 'cmkadmin',
                                                  'updated_at': 1697737946.8572102},
                                    'site': 'scooter',
                                    'tag_criticality': 'prod'},
 'lyo-rtr-4th01': {'meta_data': {'created_at': 1686772364.8024366,
                                 'created_by': 'cmkadmin',
                                 'updated_at': 1697737946.8574111}},
 'twenty-es01.adc.thegrid-walk.txt': {'meta_data': {'created_at': 1687285509.882947,
                                                    'created_by': 'cmkadmin',
                                                    'updated_at': 1697737946.8576052}}})

folder_attributes.update({})
